### ISSUE TITLE
Did you get this to work?

### ISSUE THREAD

**Issue by DougAnderson444** [nunogois/sveltekit-rust-wasm#1]
When I run `dev`, I get this error  `ENOENT: no such file or directory, open '\sveltekit-rust-wasm\node_modules\wasm\wasm.js'`

Like it's looking for 'wasm' in node_moudles instead of the vite plugin.

**Comment by DougAnderson444** [comment]
Also, when I run `dev` it gets hung up after the `wasm-pack` step, never gets to the `svelte-kit dev` step.

![image](https://user-images.githubusercontent.com/6699901/164337211-389d165b-550f-43c5-8bed-19d58f23c8f5.png)

**Comment by DougAnderson444** [comment]
Nevermind, after I cloned it seems to be working. Thanks!

**Comment by WesselvanDam** [comment]
@DougAnderson444 I am having the same issue where it hangs on `yarn dev`. I cloned it twice, but I'm not getting it to work. Is there anything else you had to do?

**Comment by DougAnderson444** [comment]
I can't remember... I ended up usign `https://github.com/wasm-tool/rollup-plugin-rust` which works pretty well
